package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/PuerkitoBio/goquery"
)

var reMultiBlank = regexp.MustCompile(`\n{3,}`)

// ConvertHTMLToMarkdown 从 HTML 提取所有文本信息
func ConvertHTMLToMarkdown(htmlPath, pageName string) (string, error) {
	f, err := os.Open(htmlPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	doc, err := goquery.NewDocumentFromReader(f)
	if err != nil {
		return "", fmt.Errorf("解析HTML失败: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# ")
	sb.WriteString(pageName)
	sb.WriteString("\n\n")

	seen := make(map[string]bool)
	collectText(doc.Find("body"), &sb, seen, 0)

	markdown := sb.String()
	markdown = reMultiBlank.ReplaceAllString(markdown, "\n\n")
	return strings.TrimSpace(markdown), nil
}

// collectText 递归收集所有可见文本
func collectText(s *goquery.Selection, sb *strings.Builder, seen map[string]bool, depth int) {
	if depth > 60 {
		return
	}

	s.Contents().Each(func(i int, child *goquery.Selection) {
		// 文本节点直接取
		if goquery.NodeName(child) == "#text" {
			text := strings.TrimSpace(child.Text())
			if text != "" {
				sb.WriteString(text)
				sb.WriteString(" ")
			}
			return
		}

		// 跳过隐藏元素
		cls := child.AttrOr("class", "")
		style := child.AttrOr("style", "")
		if strings.Contains(cls, "ax_default_hidden") ||
			strings.Contains(style, "display:none") ||
			strings.Contains(style, "visibility: hidden") {
			return
		}

		tag := goquery.NodeName(child)

		// 图片
		if tag == "img" {
			src := child.AttrOr("src", "")
			if src != "" {
				sb.WriteString("[图片: " + src + "]\n")
			}
			return
		}

		// 文本 div（带 _text 后缀的 id）
		if tag == "div" {
			id := child.AttrOr("id", "")
			if strings.HasSuffix(id, "_text") {
				text := strings.TrimSpace(child.Text())
				text = regexp.MustCompile(`\s+`).ReplaceAllString(text, " ")
				if text != "" {
					sb.WriteString(text)
					sb.WriteString("\n")
				}
				return
			}
		}

		// 递归
		collectText(child, sb, seen, depth+1)
	})
}

// ConvertAndSaveMarkdown 转换并保存
func ConvertAndSaveMarkdown(htmlPath string) (string, error) {
	pageName := strings.TrimSuffix(filepath.Base(htmlPath), ".html")
	markdown, err := ConvertHTMLToMarkdown(htmlPath, pageName)
	if err != nil {
		return "", err
	}

	mdPath := strings.TrimSuffix(htmlPath, ".html") + ".md"
	if err := os.WriteFile(mdPath, []byte(markdown), 0644); err != nil {
		return "", fmt.Errorf("保存Markdown失败: %w", err)
	}
	return mdPath, nil
}

// GenerateIndexMD 生成 Markdown 导航文件
func GenerateIndexMD(outputDir, docName string, pages []PageItem) error {
	var sb strings.Builder

	sb.WriteString("# ")
	sb.WriteString(docName)
	sb.WriteString("\n\n")
	sb.WriteString(fmt.Sprintf("共 %d 个页面\n\n", len(pages)))
	sb.WriteString("---\n\n")

	var currentFolder string
	for _, p := range pages {
		if p.Folder != "" && p.Folder != currentFolder && p.Folder != "根目录" {
			if currentFolder != "" {
				sb.WriteString("\n")
			}
			currentFolder = p.Folder
			sb.WriteString("## ")
			sb.WriteString(currentFolder)
			sb.WriteString("\n\n")
		}

		indent := ""
		if p.Level > 0 {
			indent = strings.Repeat("  ", p.Level)
		}

		pageDir := SanitizeFilename(p.Name)
		if p.Folder != "" && p.Folder != "根目录" {
			pageDir = SanitizeFilename(p.Folder) + "/" + pageDir
		}
		linkPath := pageDir + "/" + strings.TrimSuffix(p.Filename, ".html") + ".md"

		sb.WriteString(fmt.Sprintf("%s- [%s](%s)\n", indent, p.Name, linkPath))
	}

	sb.WriteString("\n---\n\n")
	sb.WriteString("*Generated by lanhu-download*\n")

	outPath := filepath.Join(outputDir, "index.md")
	return os.WriteFile(outPath, []byte(sb.String()), 0644)
}
