package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	md "github.com/JohannesKaufmann/html-to-markdown"
	"github.com/JohannesKaufmann/html-to-markdown/plugin"
)

var reHTMLComment = regexp.MustCompile(`<!--[\s\S]*?-->`)
var reScriptTag = regexp.MustCompile(`(?i)<script[^>]*>[\s\S]*?</script>`)
var reStyleTag = regexp.MustCompile(`(?i)<style[^>]*>[\s\S]*?</style>`)
var reMultiBlank = regexp.MustCompile(`\n{3,}`)

// ConvertHTMLToMarkdown 将 HTML 转为 Markdown
func ConvertHTMLToMarkdown(htmlPath string) (string, error) {
	data, err := os.ReadFile(htmlPath)
	if err != nil {
		return "", err
	}
	content := string(data)

	// 移除注释和 script/style
	content = reHTMLComment.ReplaceAllString(content, "")
	content = reScriptTag.ReplaceAllString(content, "")
	content = reStyleTag.ReplaceAllString(content, "")

	converter := md.NewConverter("", true, nil)

	// 表格插件
	converter.Use(plugin.Table())

	// 提取 body 内容
	bodyStart := strings.Index(content, "<body")
	bodyEnd := strings.LastIndex(content, "</body>")
	if bodyStart >= 0 && bodyEnd > bodyStart {
		idx := strings.Index(content[bodyStart:], ">")
		if idx >= 0 {
			content = content[bodyStart+idx+1 : bodyEnd]
		}
	}

	markdown, err := converter.ConvertString(content)
	if err != nil {
		return "", fmt.Errorf("转换失败: %w", err)
	}

	// 清理多余空行
	markdown = reMultiBlank.ReplaceAllString(markdown, "\n\n")
	markdown = strings.TrimSpace(markdown)

	// 如果内容太少，说明是纯图片页面，补充提示
	if len(markdown) < 50 {
		markdown = "（此页面主要是图片/交互组件，文本内容较少）\n\n" + markdown
	}

	return markdown, nil
}

// ConvertAndSaveMarkdown 转换 HTML 为 Markdown 并保存
func ConvertAndSaveMarkdown(htmlPath string) (string, error) {
	markdown, err := ConvertHTMLToMarkdown(htmlPath)
	if err != nil {
		return "", err
	}

	mdPath := strings.TrimSuffix(htmlPath, ".html") + ".md"
	if err := os.WriteFile(mdPath, []byte(markdown), 0644); err != nil {
		return "", fmt.Errorf("保存Markdown失败: %w", err)
	}
	return mdPath, nil
}

// GenerateIndexMD 生成 Markdown 导航文件
func GenerateIndexMD(outputDir, docName string, pages []PageItem) error {
	var sb strings.Builder

	sb.WriteString("# ")
	sb.WriteString(docName)
	sb.WriteString("\n\n")
	sb.WriteString(fmt.Sprintf("共 %d 个页面\n\n", len(pages)))
	sb.WriteString("---\n\n")

	var currentFolder string
	for _, p := range pages {
		// 文件夹分组
		if p.Folder != "" && p.Folder != currentFolder && p.Folder != "根目录" {
			if currentFolder != "" {
				sb.WriteString("\n")
			}
			currentFolder = p.Folder
			sb.WriteString("## ")
			sb.WriteString(currentFolder)
			sb.WriteString("\n\n")
		}

		indent := ""
		if p.Level > 0 {
			indent = strings.Repeat("  ", p.Level)
		}

		// 链接路径: <folder>/<page_name>/<filename>.md
		pageDir := SanitizeFilename(p.Name)
		if p.Folder != "" && p.Folder != "根目录" {
			pageDir = SanitizeFilename(p.Folder) + "/" + pageDir
		}
		linkPath := pageDir + "/" + strings.TrimSuffix(p.Filename, ".html") + ".md"

		sb.WriteString(fmt.Sprintf("%s- [%s](%s)\n", indent, p.Name, linkPath))
	}

	sb.WriteString("\n---\n\n")
	sb.WriteString("*Generated by lanhu-download*\n")

	outPath := filepath.Join(outputDir, "index.md")
	return os.WriteFile(outPath, []byte(sb.String()), 0644)
}
